### ISSUE TITLE
Parameters of other datasets

### ISSUE THREAD

**Issue by passer** [LanchJL/IAB-GZSL#2] opened 2024-06-07 04:16 UTC
Can you provide the parameters for training on other datasets?

**Comment by LanchJL** [comment] 2024-06-27 11:13
We apologize for the delayed response. 

Due to the significant time elapsed since the original work, many of the initial parameter settings have not been preserved. In the interim, we have reorganized the code and identified the appropriate parameter settings to facilitate the reproduction of results similar to those reported in the article. The configurations have been uploaded in the /configs directory. Additionally, we have updated the code to allow direct calls to our uploaded settings by running python main.py --dataset [CUB/SUN/AWA2].

**Comment by LanchJL** [comment] 2024-06-27 11:18
We are going to close this issue. If you have any other questions or suggestions, please feel free to let us know.

**Closed as completed by LanchJL** 2024-06-27 11:18 UTC
